
[cursor]
blink_interval = 500

[cursor.style]
blinking = "Always"
shape = "Beam"

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.normal]
family = "FiraCode Nerd Font Mono"
# style = "Regular"

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font Mono"
style = "Italic"

[shell]
program = "/bin/zsh"

[window]
startup_mode = "Windowed"
dynamic_padding = true
dynamic_title = true
opacity = 0.9


[window.position]
x = 200
y = 80

[window.dimensions]
columns = 151
lines = 45

[scrolling]
history = 100_000
#
# THEME GRUVBOX
#
[colors.primary]
background = "0x282828"
foreground = "0xebdbb2"

[colors.normal]
black = "0x282828"
red = "0xcc241d"
green = "0x98971a"
yellow = "0xd79921"
blue = "0x458588"
magenta = "0xb16286"
cyan = "0x689d6a"
white = "0xa89984"

[colors.bright]
black = "0x928374"
red = "0xfb4934"
green = "0xb8bb26"
yellow = "0xfabd2f"
blue = "0x83a598"
magenta = "0xd3869b"
cyan = "0x8ec07c"
white = "0xebdbb2"

